### ISSUE TITLE
Include a generic version of the diagram & include Batch Generator/Distributor

### ISSUE THREAD

**Issue by nzthiago** [programaka/batch-file-processing#3]
Discuss and possibly add a generic version of the diagram without any Azure or Components specifics, and add a distributor/batch generator. 
* Blob Storage - Storage
* Event Grid - Event Notification
* Nginx - Ingress Controller
* Redis - State Store
* App Insights - Tracing
* Service Bus - Pub Sub
* Keda - Auto Scaler
* Kubernetes - Orchestrator
* Cosmos DB - Data Store

This would not replace the existing diagram, but would be a new diagram in the Solution section to show a conceptual version of the solution. The existing diagram would then also be shown as a specific version of the solution implementation as per the sample.

Then:
* In the Generic one add Distributors sending to Storage
* In the Azure Specific one, add Batch Generator sending to Blob Storage

**Comment by programaka** [comment]
@nzthiago  I have created a generic version of the diagram, let me know what you think (https://github.com/programaka/batch-file-processing/blob/genericDiagram/images/solution-diagram-generic.png).

**Comment by nzthiago** [comment]
Thank you @programaka - that looks good! I like it that you kept the original icons and added other icons to the other section. Now that I see I think we could just replace the existing diagram with this one, what do you think?

**Comment by programaka** [comment]
Hi @nzthiago ! I am not sure if we should replace the original diagram with the generic one. We are referencing all these components like Batch Generator, KEDA, Event Grid and they are missing from the generic diagram, also the specific diagram would be more helpful in understanding this specific solution.

I added both for now to PR #21 . Could you please take a look, maybe the specific one should actually go first.

**Comment by nzthiago** [comment]
Fixed by #21
